#custom imports
################################
import ReadCingSensors
################################

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("background-color: rgb(33, 37, 41);")
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1281, 671))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.title_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_16.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_16.setFont(font)
        self.title_16.setAlignment(QtCore.Qt.AlignCenter)
        self.title_16.setObjectName("title_16")
        self.gridLayout.addWidget(self.title_16, 9, 2, 1, 1)
        self.value4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value4.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value4.setFont(font)
        self.value4.setAlignment(QtCore.Qt.AlignCenter)
        self.value4.setObjectName("value4")
        self.gridLayout.addWidget(self.value4, 2, 3, 1, 1)
        self.img_gyro_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_gyro_3.setMaximumSize(QtCore.QSize(110, 110))
        self.img_gyro_3.setText("")
        self.img_gyro_3.setPixmap(QtGui.QPixmap("pot.png"))
        self.img_gyro_3.setScaledContents(True)
        self.img_gyro_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.img_gyro_3.setObjectName("img_gyro_3")
        self.gridLayout.addWidget(self.img_gyro_3, 7, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.img_lightsensor_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_lightsensor_2.setMaximumSize(QtCore.QSize(110, 110))
        self.img_lightsensor_2.setText("")
        self.img_lightsensor_2.setPixmap(QtGui.QPixmap("lightsensor.png"))
        self.img_lightsensor_2.setScaledContents(True)
        self.img_lightsensor_2.setObjectName("img_lightsensor_2")
        self.gridLayout.addWidget(self.img_lightsensor_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.title_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_4.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_4.setFont(font)
        self.title_4.setAlignment(QtCore.Qt.AlignCenter)
        self.title_4.setObjectName("title_4")
        self.gridLayout.addWidget(self.title_4, 0, 3, 1, 1)
        self.value5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value5.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value5.setFont(font)
        self.value5.setAlignment(QtCore.Qt.AlignCenter)
        self.value5.setObjectName("value5")
        self.gridLayout.addWidget(self.value5, 2, 4, 1, 1)
        self.title_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_5.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_5.setFont(font)
        self.title_5.setAlignment(QtCore.Qt.AlignCenter)
        self.title_5.setObjectName("title_5")
        self.gridLayout.addWidget(self.title_5, 0, 4, 1, 1)
        self.title_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_2.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_2.setFont(font)
        self.title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_2.setObjectName("title_2")
        self.gridLayout.addWidget(self.title_2, 0, 1, 1, 1)
        self.img_lightsensor_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_lightsensor_4.setMaximumSize(QtCore.QSize(110, 110))
        self.img_lightsensor_4.setText("")
        self.img_lightsensor_4.setPixmap(QtGui.QPixmap("Battery.png"))
        self.img_lightsensor_4.setScaledContents(True)
        self.img_lightsensor_4.setObjectName("img_lightsensor_4")
        self.gridLayout.addWidget(self.img_lightsensor_4, 4, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.img_shinesensor_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_shinesensor_3.setMaximumSize(QtCore.QSize(110, 110))
        self.img_shinesensor_3.setText("")
        self.img_shinesensor_3.setPixmap(QtGui.QPixmap("16x2.png"))
        self.img_shinesensor_3.setScaledContents(True)
        self.img_shinesensor_3.setObjectName("img_shinesensor_3")
        self.gridLayout.addWidget(self.img_shinesensor_3, 4, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.value6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value6.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value6.setFont(font)
        self.value6.setAlignment(QtCore.Qt.AlignCenter)
        self.value6.setObjectName("value6")
        self.gridLayout.addWidget(self.value6, 5, 0, 1, 1)
        self.img_lightsensor_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_lightsensor_6.setMaximumSize(QtCore.QSize(110, 110))
        self.img_lightsensor_6.setText("")
        self.img_lightsensor_6.setPixmap(QtGui.QPixmap("TemperatureSensor.png"))
        self.img_lightsensor_6.setScaledContents(True)
        self.img_lightsensor_6.setObjectName("img_lightsensor_6")
        self.gridLayout.addWidget(self.img_lightsensor_6, 7, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.value20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value20.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value20.setFont(font)
        self.value20.setAlignment(QtCore.Qt.AlignCenter)
        self.value20.setObjectName("value20")
        self.gridLayout.addWidget(self.value20, 11, 4, 1, 1)
        self.img_shinesensor_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_shinesensor_8.setMaximumSize(QtCore.QSize(110, 110))
        self.img_shinesensor_8.setText("")
        self.img_shinesensor_8.setPixmap(QtGui.QPixmap("Enc.png"))
        self.img_shinesensor_8.setScaledContents(True)
        self.img_shinesensor_8.setObjectName("img_shinesensor_8")
        self.gridLayout.addWidget(self.img_shinesensor_8, 10, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.img_lightsensor_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_lightsensor_5.setMaximumSize(QtCore.QSize(110, 110))
        self.img_lightsensor_5.setText("")
        self.img_lightsensor_5.setPixmap(QtGui.QPixmap("bmp180.png"))
        self.img_lightsensor_5.setScaledContents(True)
        self.img_lightsensor_5.setAlignment(QtCore.Qt.AlignCenter)
        self.img_lightsensor_5.setWordWrap(False)
        self.img_lightsensor_5.setObjectName("img_lightsensor_5")
        self.gridLayout.addWidget(self.img_lightsensor_5, 7, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.value3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value3.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value3.setFont(font)
        self.value3.setAlignment(QtCore.Qt.AlignCenter)
        self.value3.setObjectName("value3")
        self.gridLayout.addWidget(self.value3, 2, 2, 1, 1)
        self.value15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value15.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value15.setFont(font)
        self.value15.setAlignment(QtCore.Qt.AlignCenter)
        self.value15.setObjectName("value15")
        self.gridLayout.addWidget(self.value15, 8, 4, 1, 1)
        self.img_shinesensor_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_shinesensor_4.setMaximumSize(QtCore.QSize(110, 110))
        self.img_shinesensor_4.setText("")
        self.img_shinesensor_4.setPixmap(QtGui.QPixmap("oled.png"))
        self.img_shinesensor_4.setScaledContents(True)
        self.img_shinesensor_4.setObjectName("img_shinesensor_4")
        self.gridLayout.addWidget(self.img_shinesensor_4, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.value1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value1.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value1.setFont(font)
        self.value1.setAlignment(QtCore.Qt.AlignCenter)
        self.value1.setObjectName("value1")
        self.gridLayout.addWidget(self.value1, 2, 0, 1, 1)
        self.img_lightsensor_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_lightsensor_3.setMaximumSize(QtCore.QSize(110, 110))
        self.img_lightsensor_3.setText("")
        self.img_lightsensor_3.setPixmap(QtGui.QPixmap("Gyro.png"))
        self.img_lightsensor_3.setScaledContents(True)
        self.img_lightsensor_3.setObjectName("img_lightsensor_3")
        self.gridLayout.addWidget(self.img_lightsensor_3, 4, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.title_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_15.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_15.setFont(font)
        self.title_15.setAlignment(QtCore.Qt.AlignCenter)
        self.title_15.setObjectName("title_15")
        self.gridLayout.addWidget(self.title_15, 6, 4, 1, 1)
        self.img_shinesensor_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_shinesensor_2.setMaximumSize(QtCore.QSize(110, 110))
        self.img_shinesensor_2.setText("")
        self.img_shinesensor_2.setPixmap(QtGui.QPixmap("shinearray.png"))
        self.img_shinesensor_2.setScaledContents(True)
        self.img_shinesensor_2.setObjectName("img_shinesensor_2")
        self.gridLayout.addWidget(self.img_shinesensor_2, 1, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.title_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_18.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_18.setFont(font)
        self.title_18.setAlignment(QtCore.Qt.AlignCenter)
        self.title_18.setObjectName("title_18")
        self.gridLayout.addWidget(self.title_18, 9, 4, 1, 1)
        self.value12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value12.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value12.setFont(font)
        self.value12.setAlignment(QtCore.Qt.AlignCenter)
        self.value12.setObjectName("value12")
        self.gridLayout.addWidget(self.value12, 8, 1, 1, 1)
        self.img_shinesensor_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_shinesensor_5.setMaximumSize(QtCore.QSize(110, 110))
        self.img_shinesensor_5.setText("")
        self.img_shinesensor_5.setPixmap(QtGui.QPixmap("bmp180.png"))
        self.img_shinesensor_5.setScaledContents(True)
        self.img_shinesensor_5.setObjectName("img_shinesensor_5")
        self.gridLayout.addWidget(self.img_shinesensor_5, 7, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.img_gyro = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_gyro.setMaximumSize(QtCore.QSize(110, 110))
        self.img_gyro.setText("")
        self.img_gyro.setPixmap(QtGui.QPixmap("Button.png"))
        self.img_gyro.setScaledContents(True)
        self.img_gyro.setObjectName("img_gyro")
        self.gridLayout.addWidget(self.img_gyro, 1, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.title_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_12.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_12.setFont(font)
        self.title_12.setAlignment(QtCore.Qt.AlignCenter)
        self.title_12.setObjectName("title_12")
        self.gridLayout.addWidget(self.title_12, 6, 1, 1, 1)
        self.img_lightsensor_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_lightsensor_8.setMaximumSize(QtCore.QSize(110, 110))
        self.img_lightsensor_8.setText("")
        self.img_lightsensor_8.setPixmap(QtGui.QPixmap("ultrasonic.png"))
        self.img_lightsensor_8.setScaledContents(True)
        self.img_lightsensor_8.setObjectName("img_lightsensor_8")
        self.gridLayout.addWidget(self.img_lightsensor_8, 10, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.value11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value11.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value11.setFont(font)
        self.value11.setAlignment(QtCore.Qt.AlignCenter)
        self.value11.setObjectName("value11")
        self.gridLayout.addWidget(self.value11, 8, 0, 1, 1)
        self.value7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value7.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value7.setFont(font)
        self.value7.setAlignment(QtCore.Qt.AlignCenter)
        self.value7.setObjectName("value7")
        self.gridLayout.addWidget(self.value7, 5, 1, 1, 1)
        self.title_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_19.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_19.setFont(font)
        self.title_19.setAlignment(QtCore.Qt.AlignCenter)
        self.title_19.setObjectName("title_19")
        self.gridLayout.addWidget(self.title_19, 9, 1, 1, 1)
        self.value10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value10.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value10.setFont(font)
        self.value10.setAlignment(QtCore.Qt.AlignCenter)
        self.value10.setObjectName("value10")
        self.gridLayout.addWidget(self.value10, 5, 4, 1, 1)
        self.title_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_3.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_3.setFont(font)
        self.title_3.setAlignment(QtCore.Qt.AlignCenter)
        self.title_3.setObjectName("title_3")
        self.gridLayout.addWidget(self.title_3, 0, 2, 1, 1)
        self.value14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value14.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value14.setFont(font)
        self.value14.setAlignment(QtCore.Qt.AlignCenter)
        self.value14.setObjectName("value14")
        self.gridLayout.addWidget(self.value14, 8, 3, 1, 1)
        self.img_shinesensor_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_shinesensor_6.setMaximumSize(QtCore.QSize(110, 110))
        self.img_shinesensor_6.setText("")
        self.img_shinesensor_6.setPixmap(QtGui.QPixmap("speaker.png"))
        self.img_shinesensor_6.setScaledContents(True)
        self.img_shinesensor_6.setObjectName("img_shinesensor_6")
        self.gridLayout.addWidget(self.img_shinesensor_6, 7, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.img_shinesensor_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_shinesensor_1.setMaximumSize(QtCore.QSize(110, 110))
        self.img_shinesensor_1.setText("")
        self.img_shinesensor_1.setPixmap(QtGui.QPixmap("shinearray.png"))
        self.img_shinesensor_1.setScaledContents(True)
        self.img_shinesensor_1.setObjectName("img_shinesensor_1")
        self.gridLayout.addWidget(self.img_shinesensor_1, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.value2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value2.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value2.setFont(font)
        self.value2.setAlignment(QtCore.Qt.AlignCenter)
        self.value2.setObjectName("value2")
        self.gridLayout.addWidget(self.value2, 2, 1, 1, 1)
        self.title_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_8.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_8.setFont(font)
        self.title_8.setAlignment(QtCore.Qt.AlignCenter)
        self.title_8.setObjectName("title_8")
        self.gridLayout.addWidget(self.title_8, 3, 2, 1, 1)
        self.title_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_11.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_11.setFont(font)
        self.title_11.setAlignment(QtCore.Qt.AlignCenter)
        self.title_11.setObjectName("title_11")
        self.gridLayout.addWidget(self.title_11, 6, 0, 1, 1)
        self.value17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value17.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value17.setFont(font)
        self.value17.setAlignment(QtCore.Qt.AlignCenter)
        self.value17.setObjectName("value17")
        self.gridLayout.addWidget(self.value17, 11, 1, 1, 1)
        self.img_gyro_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_gyro_2.setMaximumSize(QtCore.QSize(110, 110))
        self.img_gyro_2.setText("")
        self.img_gyro_2.setPixmap(QtGui.QPixmap("Gyro.png"))
        self.img_gyro_2.setScaledContents(True)
        self.img_gyro_2.setObjectName("img_gyro_2")
        self.gridLayout.addWidget(self.img_gyro_2, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.value8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value8.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value8.setFont(font)
        self.value8.setAlignment(QtCore.Qt.AlignCenter)
        self.value8.setObjectName("value8")
        self.gridLayout.addWidget(self.value8, 5, 2, 1, 1)
        self.title_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_13.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_13.setFont(font)
        self.title_13.setAlignment(QtCore.Qt.AlignCenter)
        self.title_13.setObjectName("title_13")
        self.gridLayout.addWidget(self.title_13, 6, 2, 1, 1)
        self.title_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_17.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_17.setFont(font)
        self.title_17.setAlignment(QtCore.Qt.AlignCenter)
        self.title_17.setObjectName("title_17")
        self.gridLayout.addWidget(self.title_17, 9, 3, 1, 1)
        self.value9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value9.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value9.setFont(font)
        self.value9.setAlignment(QtCore.Qt.AlignCenter)
        self.value9.setObjectName("value9")
        self.gridLayout.addWidget(self.value9, 5, 3, 1, 1)
        self.title_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_6.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_6.setFont(font)
        self.title_6.setAlignment(QtCore.Qt.AlignCenter)
        self.title_6.setObjectName("title_6")
        self.gridLayout.addWidget(self.title_6, 3, 0, 1, 1)
        self.img_shinesensor_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_shinesensor_7.setMaximumSize(QtCore.QSize(110, 110))
        self.img_shinesensor_7.setText("")
        self.img_shinesensor_7.setPixmap(QtGui.QPixmap("servoboard.png"))
        self.img_shinesensor_7.setScaledContents(True)
        self.img_shinesensor_7.setObjectName("img_shinesensor_7")
        self.gridLayout.addWidget(self.img_shinesensor_7, 10, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.title_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_7.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_7.setFont(font)
        self.title_7.setAlignment(QtCore.Qt.AlignCenter)
        self.title_7.setObjectName("title_7")
        self.gridLayout.addWidget(self.title_7, 3, 1, 1, 1)
        self.title = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 0, 0, 1, 1)
        self.value16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value16.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value16.setFont(font)
        self.value16.setAlignment(QtCore.Qt.AlignCenter)
        self.value16.setObjectName("value16")
        self.gridLayout.addWidget(self.value16, 11, 0, 1, 1)
        self.title_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_9.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_9.setFont(font)
        self.title_9.setAlignment(QtCore.Qt.AlignCenter)
        self.title_9.setObjectName("title_9")
        self.gridLayout.addWidget(self.title_9, 3, 3, 1, 1)
        self.img_gyro_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_gyro_4.setMaximumSize(QtCore.QSize(110, 110))
        self.img_gyro_4.setText("")
        self.img_gyro_4.setPixmap(QtGui.QPixmap("Enc.png"))
        self.img_gyro_4.setScaledContents(True)
        self.img_gyro_4.setObjectName("img_gyro_4")
        self.gridLayout.addWidget(self.img_gyro_4, 10, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.value13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value13.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value13.setFont(font)
        self.value13.setAlignment(QtCore.Qt.AlignCenter)
        self.value13.setObjectName("value13")
        self.gridLayout.addWidget(self.value13, 8, 2, 1, 1)
        self.value18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value18.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value18.setFont(font)
        self.value18.setAlignment(QtCore.Qt.AlignCenter)
        self.value18.setObjectName("value18")
        self.gridLayout.addWidget(self.value18, 11, 2, 1, 1)
        self.title_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_14.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_14.setFont(font)
        self.title_14.setAlignment(QtCore.Qt.AlignCenter)
        self.title_14.setObjectName("title_14")
        self.gridLayout.addWidget(self.title_14, 6, 3, 1, 1)
        self.title_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_10.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_10.setFont(font)
        self.title_10.setAlignment(QtCore.Qt.AlignCenter)
        self.title_10.setObjectName("title_10")
        self.gridLayout.addWidget(self.title_10, 3, 4, 1, 1)
        self.title_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title_20.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_20.setFont(font)
        self.title_20.setAlignment(QtCore.Qt.AlignCenter)
        self.title_20.setObjectName("title_20")
        self.gridLayout.addWidget(self.title_20, 9, 0, 1, 1)
        self.value19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.value19.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.value19.setFont(font)
        self.value19.setAlignment(QtCore.Qt.AlignCenter)
        self.value19.setObjectName("value19")
        self.gridLayout.addWidget(self.value19, 11, 3, 1, 1)
        self.img_lightsensor_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_lightsensor_7.setMaximumSize(QtCore.QSize(110, 110))
        self.img_lightsensor_7.setText("")
        self.img_lightsensor_7.setPixmap(QtGui.QPixmap("lidar.png"))
        self.img_lightsensor_7.setScaledContents(True)
        self.img_lightsensor_7.setObjectName("img_lightsensor_7")
        self.gridLayout.addWidget(self.img_lightsensor_7, 10, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.img_lightsensor_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.img_lightsensor_1.setMaximumSize(QtCore.QSize(110, 110))
        self.img_lightsensor_1.setText("")
        self.img_lightsensor_1.setPixmap(QtGui.QPixmap("lightsensor.png"))
        self.img_lightsensor_1.setScaledContents(True)
        self.img_lightsensor_1.setObjectName("img_lightsensor_1")
        self.gridLayout.addWidget(self.img_lightsensor_1, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 28))
        self.menubar.setObjectName("menubar")
        self.menuPort = QtWidgets.QMenu(self.menubar)
        self.menuPort.setObjectName("menuPort")
        self.menuConnect = QtWidgets.QMenu(self.menubar)
        self.menuConnect.setObjectName("menuConnect")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionWebsite = QtWidgets.QAction(MainWindow)
        self.actionWebsite.setObjectName("actionWebsite")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionTroubleshooting = QtWidgets.QAction(MainWindow)
        self.actionTroubleshooting.setObjectName("actionTroubleshooting")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionConfig = QtWidgets.QAction(MainWindow)
        self.actionConfig.setObjectName("actionConfig")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.actionExitApp = QtWidgets.QAction(MainWindow)
        self.actionExitApp.setObjectName("actionExitApp")
        self.menuPort.addAction(self.actionTroubleshooting)
        self.menuPort.addAction(self.actionWebsite)
        self.menuPort.addAction(self.actionAbout)
        self.menuConnect.addAction(self.actionConfig)
        self.menuConnect.addAction(self.actionExitApp)
        self.menubar.addAction(self.menuConnect.menuAction())
        self.menubar.addAction(self.menuPort.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #Custom code    
        ################################
        self.actionAbout.triggered.connect(lambda: ReadCingSensors.about_open())
        self.actionWebsite.triggered.connect(lambda: ReadCingSensors.site_open())
        self.actionTroubleshooting.triggered.connect(lambda: ReadCingSensors.troubleshooting_open())
        self.actionExitApp.triggered.connect(lambda: sys.exit())
        self.actionConfig.triggered.connect(lambda: ReadCingSensors.config_open())
        QtCore.QTimer.singleShot(100, self.updateData)
        ################################

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cing Checker"))
        self.title_16.setText(_translate("MainWindow", "LightSensor 1"))
        self.value4.setText(_translate("MainWindow", "Loading value"))
        self.title_4.setText(_translate("MainWindow", "LightSensor 1"))
        self.value5.setText(_translate("MainWindow", "Loading value"))
        self.title_5.setText(_translate("MainWindow", "Button"))
        self.title_2.setText(_translate("MainWindow", "Light sensor 2"))
        self.value6.setText(_translate("MainWindow", "Loading value"))
        self.value20.setText(_translate("MainWindow", "Loading value"))
        self.value3.setText(_translate("MainWindow", "Loading value"))
        self.value15.setText(_translate("MainWindow", "Loading value"))
        self.value1.setText(_translate("MainWindow", "Loading value"))
        self.title_15.setText(_translate("MainWindow", "Potentiometer"))
        self.title_18.setText(_translate("MainWindow", "LightSensor 1"))
        self.value12.setText(_translate("MainWindow", "Loading value"))
        self.title_12.setText(_translate("MainWindow", "Barometric Pressure Sensor"))
        self.value11.setText(_translate("MainWindow", "Loading value"))
        self.value7.setText(_translate("MainWindow", "Loading value"))
        self.title_19.setText(_translate("MainWindow", "Lidar"))
        self.value10.setText(_translate("MainWindow", "Loading value"))
        self.title_3.setText(_translate("MainWindow", "LightSensor 1"))
        self.value14.setText(_translate("MainWindow", "Loading value"))
        self.value2.setText(_translate("MainWindow", "Loading value"))
        self.title_8.setText(_translate("MainWindow", "Oled"))
        self.title_11.setText(_translate("MainWindow", "Temp sensor"))
        self.value17.setText(_translate("MainWindow", "Loading value"))
        self.value8.setText(_translate("MainWindow", "Loading value"))
        self.title_13.setText(_translate("MainWindow", "Altitude Sensor"))
        self.title_17.setText(_translate("MainWindow", "LightSensor 1"))
        self.value9.setText(_translate("MainWindow", "Loading value"))
        self.title_6.setText(_translate("MainWindow", "Gyro"))
        self.title_7.setText(_translate("MainWindow", "Accelerometer"))
        self.title.setText(_translate("MainWindow", "Light sensor 1"))
        self.value16.setText(_translate("MainWindow", "Loading value"))
        self.title_9.setText(_translate("MainWindow", "16x2 display"))
        self.value13.setText(_translate("MainWindow", "Loading value"))
        self.value18.setText(_translate("MainWindow", "Loading value"))
        self.title_14.setText(_translate("MainWindow", "IO expander"))
        self.title_10.setText(_translate("MainWindow", "Battery"))
        self.title_20.setText(_translate("MainWindow", "LightSensor 1"))
        self.value19.setText(_translate("MainWindow", "Loading value"))
        self.menuPort.setTitle(_translate("MainWindow", "Help"))
        self.menuConnect.setTitle(_translate("MainWindow", "Menu"))
        self.actionWebsite.setText(_translate("MainWindow", "Visit robotcing.sk"))
        self.actionAbout.setText(_translate("MainWindow", "About Robot Cing"))
        self.actionTroubleshooting.setText(_translate("MainWindow", "Troubleshooting"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionConfig.setText(_translate("MainWindow", "Config"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))
        self.actionExitApp.setText(_translate("MainWindow", "Exit"))

    #Custom code
    ################################
    def updateData(self):
        ReadCingSensors.update(self)
        QtCore.QTimer.singleShot(90, self.updateData)
    ################################
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
